// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025. 01. 28. 12:32:59
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg4 from "./../../woonuxt_base/tailwind.config.ts";
const config = [
{"content":{"files":["/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","./components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/plugins/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/composables/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/utils/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/app.config.{js,ts,mjs}"]}},
{},
{"content":{"files":["/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/app/plugins/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/composables/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/utils/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/app/app.config.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/KoreAgroWoonuxt/woonuxt_base/app/app/spa-loading-template.html"]}},
cfg4
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;